services:
  server:
    build: .
    command: /bin/bash /engine/scripts/entrypoint.sh
    volumes:
      - .:/engine
      - ~/.ssh:/root/.ssh
    ports:
      - "8000:8000"
    container_name: feoh
    environment:
      - PATH=/emsdk:/emsdk/upstream/emscripten:${PATH}
    working_dir: /engine
